"""Tests for tools/dump_defaults.py — the CONFIG_DEFAULTS.md generator."""

from __future__ import annotations

import os
import sys

import pytest

# Ensure tools/ is importable
_TOOLS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "tools")
if _TOOLS_DIR not in sys.path:
    sys.path.insert(0, _TOOLS_DIR)

import dump_defaults  # noqa: E402


class TestGenerator:
    """Tests for the defaults documentation generator."""

    def test_generate_returns_markdown(self):
        """generate() returns a non-empty Markdown string."""
        md = dump_defaults.generate()
        assert isinstance(md, str)
        assert len(md) > 100

    def test_contains_auto_generated_header(self):
        """Output starts with the auto-generated warning comment."""
        md = dump_defaults.generate()
        assert md.startswith("<!-- AUTO-GENERATED by tools/dump_defaults.py")

    def test_contains_planner_section(self):
        """Output has a Planner subsystem section."""
        md = dump_defaults.generate()
        assert "## Planner (`planner.defaults`)" in md

    def test_contains_factory_section(self):
        """Output has a Factory subsystem section."""
        md = dump_defaults.generate()
        assert "## Factory (`factory.defaults`)" in md

    def test_planner_entries_present(self):
        """Key planner constants appear in the output."""
        md = dump_defaults.generate()
        for name in [
            "DEFAULT_MODEL",
            "DEFAULT_REASONING_EFFORT",
            "POLL_DEADLINE_S",
            "MAX_COMPILE_ATTEMPTS",
            "COMPILE_HASH_HEX_LENGTH",
            "SHELL_OPERATOR_TOKENS",
        ]:
            assert f"`{name}`" in md, f"Missing planner entry: {name}"

    def test_factory_entries_present(self):
        """Key factory constants appear in the output."""
        md = dump_defaults.generate()
        for name in [
            "DEFAULT_MAX_ATTEMPTS",
            "RUN_ID_HEX_LENGTH",
            "MAX_FILE_WRITE_BYTES",
            "GIT_TIMEOUT_SECONDS",
            "ARTIFACT_RUN_SUMMARY",
            "ALLOWED_STAGES",
        ]:
            assert f"`{name}`" in md, f"Missing factory entry: {name}"

    def test_entry_count(self):
        """Output contains at least 50 table rows (one per inventory item)."""
        md = dump_defaults.generate()
        # Each entry row starts with "| `" (name column)
        rows = [line for line in md.splitlines() if line.startswith("| `")]
        assert len(rows) >= 50, f"Expected >= 50 rows, got {len(rows)}"

    def test_determinism_tag_present(self):
        """Determinism-sensitive entries are tagged."""
        md = dump_defaults.generate()
        # DEFAULT_MODEL is det-tagged
        for line in md.splitlines():
            if "`DEFAULT_MODEL`" in line:
                assert "yes" in line, "DEFAULT_MODEL should have det=yes"
                break
        else:
            pytest.fail("DEFAULT_MODEL row not found")

    def test_safety_tag_present(self):
        """Safety-invariant entries are tagged."""
        md = dump_defaults.generate()
        for line in md.splitlines():
            if "`MAX_FILE_WRITE_BYTES`" in line:
                assert "yes" in line, "MAX_FILE_WRITE_BYTES should have safety=yes"
                break
        else:
            pytest.fail("MAX_FILE_WRITE_BYTES row not found")

    def test_check_mode_passes(self, tmp_path):
        """--check mode passes when the file matches generated output."""
        md = dump_defaults.generate()
        out_path = str(tmp_path / "CONFIG_DEFAULTS.md")
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(md)
        # Patch the output path and verify check would pass
        original = dump_defaults._OUTPUT_PATH
        try:
            dump_defaults._OUTPUT_PATH = out_path
            with open(out_path, "r", encoding="utf-8") as fh:
                assert fh.read() == md
        finally:
            dump_defaults._OUTPUT_PATH = original

    def test_extract_entries_planner(self):
        """_extract_entries returns entries for the planner module."""
        import planner.defaults as pd
        entries = dump_defaults._extract_entries(pd)
        names = {e.name for e in entries}
        assert "DEFAULT_MODEL" in names
        assert "POLL_DEADLINE_S" in names
        assert len(entries) >= 24

    def test_extract_entries_factory(self):
        """_extract_entries returns entries for the factory module."""
        import factory.defaults as fd
        entries = dump_defaults._extract_entries(fd)
        names = {e.name for e in entries}
        assert "DEFAULT_MAX_ATTEMPTS" in names
        assert "ARTIFACT_RUN_SUMMARY" in names
        assert len(entries) >= 26
